parameter_files/ProjectParameters_Indices2022Q4.yml

For these project parameters, I used the `2021Q4` indices parameters as a baseline, but changed:
* The list of scenarios to that which is in the `workflow.data.preparation/config.yml` for `2022Q4`
* All references from 2021 to 2022
* The `select_scenario` and `scenario_other` to their analogous values in the updated scenarios

Add `2022Q4` Project Parameters

---

parameter_files/ProjectParameters_GENERAL.yml

This pretty awkward implementation...
I need to bump the `GENERAL.yml` file to point to the `2022Q4` information. This means that there is a commit SHA of `workflow.transition.monitor` where GENERAL points to `2021Q4` and corresponds to the `rmi_pacta:2021q4_1.0.0` image, 
and then there will also be a SHA that points to `2022Q4` and corresponds to the `rmi_pacta:2022q4_1.0.0`. 
Does this mean that we can only have the `GENERAL` initiative use EITHER `2021Q4` or `2022Q4`, but can't have users switch between them?

Bump `ProjectParameters_GENERAL.yml` to `2022Q4`

---

Dockerfile

The Rocker base image has a bunch of labels assigned in it, which our image inherits and they are then displayed in the repositories metadata (e.g. [here](https://github.com/RMI-PACTA/workflow.transition.monitor/pkgs/container/workflow.transition.monitor/110330691?tag=nightly)). This sets the minimal set of labels suggested by GitHub [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images).
We may want to consider also re-setting (possibly by setting them to `""`?) the other labels set by Rocker? e.g.
```json
"labels": {
"org.opencontainers.image.source": "https://github.com/rocker-org/rocker-versioned2",
"org.opencontainers.image.title": "rocker/r-ver",
"org.opencontainers.image.revision": …
```

add minimal Docker image labels for GHCR

---

parameter_files/WebParameters_docker.yml
parameter_files/WebParameters_local.yml

The `new_data` parameter was used in previous versions of `PACTA_analysis` to trigger an on-the-fly processing of some data files (e.g. currencies) rather than relying on preprocessed files, but that ability has been completely removed was the current/modern data.prep process was created.
https://github.com/RMI-PACTA/PACTA_analysis/blob/9f760b8319791db07dc07317ea844965980b181f/web_tool_script_1.R#L37-L44

remove `new_data` parameter that is defunct

---

parameter_files/ProjectParameters_GENERAL.yml

Removing data path in GENERAL Template file, since this caused portfolios to _always_ use that data, even if a different holdings date is used in the portfolio parameters file.

remove data path reference

---

Dockerfile

While freezing the R package dependencies at a certain date makes sense, using the most up to date version of {pak} to install those dependencies is ideal.

install most recent version of {pak}

---

parameter_files/WebParameters_docker.yml
parameter_files/WebParameters_local.yml
web_tool_script_3.R

In the `workflow.transition.monitor` use case, the `project_name` parameter is set in the `parameter_files/WebParameters_docker.yml` and/or `parameter_files/WebParameters_local.yml` files, but it is never used except for being passed as an argument to `create_interactive_report()` which also never uses the argument. Additionally, it is set by default to `"working_dir"` in both cases, which suggests that this is a long leftover option that is not being used as expected. `create_interactive_report()` sets a default value for its `project_name` argument (which is also set to `"working_dir"` by default), so removing that argument from the call in `web_tool_script_3.R` should not have any negative effect. I would suggest that once this PR is merged, that the `project_name` argument also be …

remove `project_name` parameter

---

web_tool_script_3.R

The R pkg {config} should never be loaded with `library(config)` because its functions will override common, important base R functions. Not sure how we never noticed this.

do not load R pkg {config}

---

web_tool_script_1.R

`file_location` is the same as `analysis_inputs_path`, and only used in the following few lines to load input data
FYI: the diff for this commit looks like more than it is (because of the algorithm that determines what changed and what it was related to)... I only removed the line setting `file_location` to the value of `analysis_inputs_path`, and after that only changed the argument `file_location` to `analysis_inputs_path` in following function calls.

remove redundant variable

---

web_tool_script_1.R

depends on https://github.com/RMI-PACTA/pacta.portfolio.audit/pull/17
depends on https://github.com/RMI-PACTA/pacta.portfolio.audit/pull/18
Use the new explicit arguments of `get_entity_info()` and `get_input_files()` rather than depend on the global variables existing.

use explicit arguments rather than implicit global variables

---

Dockerfile

closes #225
Update R packages snapshot date to 2023-10-30 so that it includes dbplyr v2.4.0

Update R packages snapshot date to 2023-10-30

---

DESCRIPTION
LICENSE
LICENSE.md

This PR does all the appropriate things related to adding a license to the repo, including:
- adding a LICENSE file
- adding a LICENSE.md file
- properly specifying the license in the DESCRIPTION file
depends on #231

Add license

---

build/build_private_docker.sh

Fixes path to pacta-data in private docker image. Previously, build would COPY data to timestamped directory
(`/pacta-data/2023Q4_20240218T231047Z`). Now copies to path expected by PACTA (`/pacta-data/2023Q4`).
No associated issue.
Relates to #247

fix(docker): fix path to pacta-data

---

build/build_with_tag.sh

Adds an image name argument to `build_with_tag.sh` which allows specifying an image name other than `rmi_pacta`
Closes: #237

build(docker): #237 Allow image name in build script

---

parameter_files/ProjectParameters_PA2024CH.yml

parameters for PA2024CH

---

.github/workflows/build-Docker-image-triggers.yml
README.md

closes #274
also added name "Docker build & test" to the `build-Docker-image-triggers.yml` so we get a better looking badge:
[![.github/workflows/build-Docker-image-triggers.yml](https://github.com/RMI-PACTA/workflow.transition.monitor/actions/workflows/build-Docker-image-triggers.yml/badge.svg)](https://github.com/RMI-PACTA/workflow.transition.monitor/actions/workflows/build-Docker-image-triggers.yml)

add badges to README

---

web_tool_script_3.R

this is a bit of a hack, but it makes manual/step-through testing a bit easier by aligning the object names in the global environment with the parameter names in `create_interactive_report()`

facilitate easier testing by aligning parameter names

---

.github/workflows/build-Docker-image-triggers.yml
.github/workflows/build-and-push-Docker-image.yml
.github/workflows/build-push-private.yml

Adds code to export information about build and testing status to use comment action from RMI-PACTA/actions repo

Use new comment action with history

---

parameter_files/WebParameters_docker.yml
parameter_files/WebParameters_local.yml

`project_location_ext` is an old parameter used in `PACTA_analysis` that is no longer in use in any of our active repos (except here, and `pacta.portfolio.utils::set_web_parameters()` which is being removed in https://github.com/RMI-PACTA/pacta.portfolio.utils/pull/26)
https://github.com/search?q=org%3ARMI-PACTA+project_location_ext+NOT+is%3Aarchived&type=code
ℹ️ As I understand it, the working directory is used implicitly instead of what this parameter used to set explicitly.

remove `project_location_ext`

---

.github/workflows/build-push-private.yml
Dockerfile

Use a more recent date for pinning R packages, which include `bookdown >= 0.38`
Closes: #296

build(docker): #296 change pin date for R packages

---

build/config/rmi_pacta_2023q4_general.json
build/config/rmi_pacta_2023q4_pa2024ch.json

Updates applied for `GENERAL` and `PA2024CH` pointing to `2023Q4` data. 
Azure directory: `2023Q4_20240424T120055Z`
Built from: https://github.com/RMI-PACTA/workflow.data.preparation/commit/5a96cc36b9d343b66bef2d518c6fb340eb686979

feat: update `GENERAL` and `PA2024CH` build configs to point to latest `2023Q4` data

---

.github/workflows/build-Docker-image-triggers.yml
.github/workflows/build-push-private.yml
build/config/rmi_pacta_2022q4_general.json
build/config/rmi_pacta_2023q4_general.json
build/config/rmi_pacta_2023q4_pa2024ch.json

Add index preparation to steps of private docker image build.
Keeps pacta code and data in sync with what is included between index prep and CTM image
Depends on https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/pull/97

Include index prep

---

Dockerfile

Removes uneeded build args from Dockerfile.
The build args are holdovers from before we used `pak` to manage and install dependencies, but `pak` allows us to specify non-`main` branches in the `Remotes:` of `DESCRIPTION`, meaning that the docker image is dependent upon what is committed in code, rather than arguments passed tot he process at build time.
As an example of how to use a non-`main` (technically, non-default GH branch) dependency:
we might change this example DESCRIPTION:
```
Imports: 
config,
dplyr,
pacta.executive.summary, 
pacta.portfolio.allocate,  
rmarkdown, 
shiny
Remotes: 
RMI-PACTA/pacta.executive.summary, 
RMI-PACTA/pacta.portfolio.allocate, 
```
to read as:
```
Imports: 
config,
dplyr,
pacta.executive.summary, 
pacta.portfolio.allocate,  
rmarkdown, 
shiny
Remotes: …
```

Remove unneeded build args

---

.github/workflows/build-Docker-image-triggers.yml

Workflow was renamed in https://github.com/RMI-PACTA/actions/pull/82
Resolves failing checks on `main`: https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/9166710495

Update called workflow

---

DESCRIPTION
web_tool_script_2.R

Adapting to https://github.com/RMI-PACTA/pacta.portfolio.allocate/pull/49/
Depends on and incorporates changes needed for https://github.com/RMI-PACTA/pacta.portfolio.allocate/pull/49
CLoses #317

adapt to new function signatures in `pacta.portfolio.allocate`

---

build/config/rmi_pacta_2023q4_pa2024ch.json

Only run DE and FR for `bank` and `other` peer groups (to confirm "other" doesn't get peer results).
Closes #318 (hopefully)

Reduce Testing Matrix

---

.github/workflows/build-push-private.yml
DESCRIPTION
build/config/rmi_pacta_2023q4_pa2024ch.json
web_tool_script_3.R

With the new SBTi calculation we need to pass to executive summary the directory when pacta inputs are because that is where the file with SBTi data merged with FactSet data will live.
This depends on a PR in executive summary: https://github.com/RMI-PACTA/pacta.executive.summary/pull/346. This PR needs to be merged first for this one to work. Also, the `pacta-data` folder needs to contain `fin_data_net_zero_targets.csv` and has to use the most recent version of the testing `user_data` (https://github.com/RMI-PACTA/user_results/pull/24/files/f75b9955f640a74124003e524a6a5789d9b616b8..355ef24f21422238c88be9ad6ff571ef2d5e56db).

Add a parameter to executive summary calculations

---

DESCRIPTION
build/config/rmi_pacta_2023q4_general.json
build/config/rmi_pacta_2023q4_pa2024ch.json

The newly created data directory now contains APS and STEPS scenarios for WEO 2023 for the aviation, cement and steel sectors. 
Importantly also, we had to update paths to the new (real) `peer` files, as those had to be re-run with those same latest scenarios. 
With these scenarios missing, the executive summary couldn't render correctly. 
Relates to:
RMI-PACTA/workflow.data.preparation/pull/238
RMI-PACTA/workflow.data.preparation/pull/237
RMI-PACTA/workflow.data.preparation/pull/236
RMI-PACTA/pacta.scenario.data.preparation/pull/61
RMI-PACTA/pacta.scenario.data.preparation/pull/63

config: point `pa2024ch` to data prep with new weo 2023 scenarios

---

.github/workflows/build-push-private.yml

Pack the `pacta-data` and `templates.transition.monitor` directories that were used to build the image, and upload archive to Azure Blob container.
Closes #348.

add archive export for inputs

---

build/config/rmi_pacta_2023q4_general.json
build/config/rmi_pacta_2023q4_pa2024ch.json

The `financial_data` output is now filtered for cases where `shares_all_classes > 0`:
Relates to https://github.com/RMI-PACTA/pacta.data.preparation/pull/33
Leaving as a draft until I am able to re-run `peer_results` to confirm that CI/CD build are functional.

config: bump `2023Q4` configuration to latest run of data preparation

---

.github/workflows/build-push-private.yml

Similar to https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/pull/110
It seems that the `azure/cli` image removed a bunch of unix utils, including `tar`, so similar to liked PR, I'm breaking the step into two, one to run the unix command, and another for the `az` part of things. 
in this case, using `tar` to prepare the inputs archive, and then `az` in the second to move it to persistent storage.

Move packing inputs archive to separate step

---

DESCRIPTION
build/config/rmi_pacta_2023q4_pa2024ch.json

Not to be merged until dependencies are resolved.
Updates build configuration to use latest version of testing RE files.
Depends On:

Update dependencies to include real estate

---

.github/workflows/build-Docker-image-triggers.yml
build/config/rmi_pacta_2023q4_pa2024ch_sectoral.json
parameter_files/ProjectParameters_PA2024CH_sectoral.yml

Add testing configurations for Sectoral Reports for PA2024 CH 
Depends on https://github.com/RMI-PACTA/templates.transition.monitor/pull/51

Add build config for sectoral reports

---

Dockerfile

Tested here: https://github.com/RMI-PACTA/workflow.transition.monitor/pull/373
Required by: https://github.com/RMI-PACTA/pacta.executive.summary/pull/376

docker image gains LaTeX packages necessary for DE rendering

---

.github/workflows/build-push-private.yml
DESCRIPTION
build/config/rmi_pacta_2023q4_pa2024ch.json

In support of https://github.com/RMI-PACTA/pacta.portfolio.report/issues/97
Allows for testing user_results directories at non-standard blob locations.

Add testing files with extra JSON Array

---

web_tool_script_1.R

- related https://github.com/RMI-PACTA/workflow.pacta/pull/108
resolves ADO#12306

remove invalid holdings after audit

---

.github/workflows/build-push-private.yml

- reverts #397 
This bug seems to have been fixed on Azure's side https://github.com/Azure/azure-cli/issues/30635#issuecomment-2651312166
Now there's a new unrelated CI error:
``` shell
Determining the default branch
Retrieving the default branch name
Bad credentials - https://docs.github.com/rest
Waiting 16 seconds before trying again
Retrieving the default branch name
Bad credentials - https://docs.github.com/rest
Waiting 18 seconds before trying again
Retrieving the default branch name
Error: Bad credentials - https://docs.github.com/rest
```

revert #397 which does not appear to be necessary anymore
