RMI-PACTA/workflow.transition.monitor

.github/workflows/nightly-docker-build.yml
.github/workflows/test-Docker-build.yml
Dockerfile
README.md
build/build_with_tag.sh

@jdhoffa and @AlexAxthelm I think this is the minimal switch to installing our PACTA R packages from their public GH repos, plus a few minor fixes and normalization of quotes etc.
I have an idea for using a re-useable GH action just for building the Docker image, and calling it from other actions that manage appropriate actions depending on the trigger for it, but I think better to do that in a follow-on PR.

Install R pkgs from gh

---

.github/workflows/build-Docker-image-on-push-to-pr.yml

This should allow the GH Action to once again find the previous comment and update it rather than creating a new comment

update author name for GH Actions

---

Dockerfile

reset image labels inherited from `rocker/r-vers`

---

web_tool_script_1.R
web_tool_script_2.R
web_tool_script_3.R

see https://github.com/RMI-PACTA/pacta.portfolio.utils/pull/13

remove use of deprecated argument `dataprep_timestamp`

---

parameter_files/AnalysisParameters.yml
parameter_files/ProjectParameters.yml
parameter_files/ProjectParameters_GENERAL.yml
parameter_files/ProjectParameters_Indices2021Q4.yml
parameter_files/ProjectParameters_Indices2022Q4.yml
parameter_files/ProjectParameters_MFM2022.yml
parameter_files/ProjectParameters_PA2022BR.yml
parameter_files/ProjectParameters_PA2022CH.yml
parameter_files/ProjectParameters_PA2022FL.yml
parameter_files/ProjectParameters_market_reports.yml
web_tool_script_2.R

finish up the process begun here:
https://github.com/RMI-PACTA/pacta.portfolio.analysis/pull/233
and here:
https://github.com/RMI-PACTA/workflow.transition.monitor/pull/154

stop using `grouping_variables` which has been banished

---

Dockerfile

remove `RUN exit 0` from Dockerfile

---

build/Dockerfile.private
build/build_private_docker.sh

New image builds off public image but adds real data and report templates
Closes: #246

build(docker): #246 Add docker image to supplement public image

---

build/build_private_docker.sh
build/tag-and-push.sh

Check that the az cli is installed and logged in prior to running any commands that depend on it.
Closes: #74

feat(docker): #74 check for logged-in az cli

---

.github/workflows/build-push-private.yml

Version bumps

---

.github/workflows/build-Docker-image-triggers.yml
.github/workflows/build-push-private.yml

Artifact upload works differently in v4.
Closes #264 
Followup to #268

Resolve artifact upload from version bumps

---

.github/workflows/build-Docker-image-triggers.yml

closes #266 
@AlexAxthelm not sure if this would work?

add `workflow_dispatch` trigger for manual run of tests

---

.github/workflows/build-Docker-image-triggers.yml
.github/workflows/build-and-push-Docker-image.yml

Add GHCR image to docker comment

---

web_tool_script_3.R

Relates to https://github.com/RMI-PACTA/pacta.portfolio.report/pull/60

feat: `twodi_sectors` renamed to `pacta_sectors`

---

Dockerfile
web_tool_script_3.R

add data checks before creating a report and warn of problems

---

web_tool_script_3.R

following #298, this all checks for the peer user data when appropriate

check for peer user results when appropriate

---

build/config/rmi_pacta_2022q4_general.json

Edit:
The primary addition for this config update is a fresh pull of FactSet data, which includes additional coverage and improved fund composition data. 
The data is now also built using the (new) completely public data preparation process:
https://github.com/RMI-PACTA/workflow.data.preparation
and
https://github.com/RMI-PACTA/pacta.data.preparation

feat: update GENERAL build config to point to latest 2022Q4 data

---

web_tool_script_3.R

Needs https://github.com/RMI-PACTA/pacta.executive.summary/pull/307 to be merged in first.

Remove real estate parameters

---

build/config/rmi_pacta_2023q4_pa2024ch.json

Relates to https://github.com/RMI-PACTA/user_results/pull/24 at fa895b7

Update reference to user results directory

---

DESCRIPTION
build/config/rmi_pacta_2023q4_pa2024ch.json
web_tool_script_3.R

Closes #325 
Depends on https://github.com/RMI-PACTA/pacta.executive.summary/pull/335

Point to testing files with no indices

---

.github/workflows/build-push-private.yml
DESCRIPTION
build/config/rmi_pacta_2023q4_pa2024ch.json

Include sbti file

---

.github/workflows/build-Docker-image-triggers.yml

Final Reports are delivered, so no further development expected.
Suppresses, but does NOT resolve #390

Disable CI testing for `PA2024CH_sectoral`

---

Dockerfile

Match `FROM` and `AS` casing

---

.github/workflows/build-Docker-image-triggers.yml

Disable tests for PA2024CH
